FROM node:22-bookworm-slim

WORKDIR /app

ENV HUSKY=0

COPY package.json package-lock.json ./
COPY apps/backend/package.json apps/backend/
COPY apps/frontend/package.json apps/frontend/

RUN npm ci

COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend

ENV DATABASE_URL="postgresql://refund:refund@postgres:5432/refund"

RUN npx prisma generate

EXPOSE 3333

ENTRYPOINT ["sh", "docker-entrypoint.dev.sh"]
